### PR TITLE
Porting Switch2OSM to MkDocs from Jekyll

### LINKED ISSUE #224: Implementation of the multilanguage support for Switch2OSM.
Dear all,

I want to share a ready-to-use implementation of the multilanguage support for Switch2OSM.

https://github.com/Andygol/switch2osm-mkdocs   
(see demo: https://andygol.github.io/switch2osm-mkdocs/)

There were several proposals to do this, #24 and #92. Unfortunately, it was very difficult to implement this with Jekyll. So, I opted for MkDocs, because it helps to do this with ease and have some extra features out of the box:

- day/night theme switcher
- search
- syntax highlighting
- info boxes
- auto deployment and other

I’ve moved the content and cleaned up formatting of the source *.md files, and set up Transifex project to support translations. I neither copied the current design nor rewrote some outdated parts (like the part about using OpenLayers, which references an outdated version of the library, which makes the code used for the library not working).

If you like what I’ve done, I could help with porting my work to the main repository.

I hope this update will help to engage the community to provide localized materials that help with switching to using OSM globally.

### PR DESCRIPTION
**Pull request by Andygol**
This PR closes #224.

If necessary, the translation of texts can be organized through the integration with Transifex (use transifex.yml)

Feel free to adjust this PR if needed.

### CODE REVIEW

**Comment by pnorman** [comment]
This has hundreds of commits and file changes. I'm not sure how this is reviewable.

A PR should do one thing. I recommend doing one PR for changing to Jekyll, if that's what we want to do, another PR to add translation support, and then any translations can be added in the mechanism we decide for them.

**Comment by Andygol** [comment]
To be honest, I'm a little confused by this answer. The offer to switch to MkDocs with a working example has been around for half a year. Since its introduction, it has only been mentioned that a pull request is needed, but it is not clear who should do it.

On my part, this PR was an attempt to move the issue from its current state of limbo.

It is worth noting the help from @Firefishy in creating github actions for building a container with a working site (https://github.com/Andygol/switch2osm-mkdocs/pull/37). So, by and large, it is enough just to replace one container with another one used for the main site, for the changes to take effect. 


I also don't think this PR is a perfect solution, but I can suggest the following transition plan:
- The **switch2osm** repo in its current state (jekyll version) is archived and renamed to preserve historical artifacts.
- Forking (or copying content) from https://github.com/Andygol/switch2osm-mkdocs to https://github.com/switch2osm/switch2osm. This can be either one big commit or multiple commits split into stages, as described in the comment above. (Personally, I'm more inclined towards one global commit).
- Appropriate changes are made to the `mkdocs.yml` file to reflect the current repo
- Integration with Transifex is being configured to support translations in other languages. At https://app.transifex.com/openstreetmap/ a corresponding project is created for this. If necessary, it can be any other website that offers similar services.

**Comment by Firefishy** [comment]
@Andygol The work to move it to mkdocs looks excellent to me. I contact the other contributors of the site to get agreement, if I get agreement I will push this live.

**Comment by SomeoneElseOSM** [comment]
I'm sure that I commented somewhere on this with something like "I'd love to see it available in other languages, but can't really comment on potential issues with mkdocs vs Jekyll" but can't see where I said that.

If mkdocs content is about as easy to edit and test as jekyll content, then I'd have no objections.  Preferably for me it wouldn't require Yet Another Package Manager, but mkdocs [looks](https://packages.ubuntu.com/jammy/mkdocs) [promising](https://packages.debian.org/bullseye/mkdocs).

**Comment by Andygol** [comment]
@Firefishy could you reopen the PR.

Something goes wrong when I pushed updates to the fork 😞

**Comment by Firefishy** [comment]
@Andygol "branch has no history in common with switch2osm:master". It will not let me re-open.

**Comment by Andygol** [comment]
Looks like I need to do a new PR

**Pull request closed without merging**
